"""
Comprehensive Hydroponic Crop Database
Contains 100+ crops with detailed growing parameters for hydroponics
Organized by category with climate, seasonal, and regional recommendations
"""

from datetime import datetime
from typing import List, Dict, Optional
import math

# ==================== CROP DATABASE ====================

HYDROPONIC_CROPS = {
    # ==================== LEAFY GREENS ====================
    "lettuce_butterhead": {
        "name": "Butterhead Lettuce",
        "emoji": "🥬",
        "category": "leafy_greens",
        "scientific_name": "Lactuca sativa var. capitata",
        "description": "Tender, sweet leaves with buttery texture. Perfect for hydroponics beginners.",
        "temperature_range": {"min": 15, "max": 22, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 0.8, "max": 1.2, "optimal": 1.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 45,
        "yield_per_sqm": 4.5,
        "profit_margin": 35,
        "difficulty_level": "beginner",
        "water_consumption": "low",
        "nutrient_requirements": {"N": "medium", "P": "low", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Wick"],
        "growing_seasons": ["spring", "fall", "winter"],
        "climate_zones": ["temperate", "subtropical", "mediterranean"],
        "indian_regions": ["North India", "Northeast", "Hill Stations"],
        "indian_states": ["Himachal Pradesh", "Uttarakhand", "Kashmir", "Sikkim", "Meghalaya"],
        "best_months_india": [1, 2, 3, 10, 11, 12],
        "common_pests": ["Aphids", "Slugs", "Whiteflies"],
        "common_diseases": ["Downy Mildew", "Tip Burn", "Bottom Rot"],
        "companion_crops": ["Carrots", "Radishes", "Strawberries"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Vitamin A", "Vitamin K", "Folate"],
        "tips": "Maintain consistent temperature to prevent bolting. Harvest outer leaves first.",
    },
    "lettuce_romaine": {
        "name": "Romaine Lettuce",
        "emoji": "🥬",
        "category": "leafy_greens",
        "scientific_name": "Lactuca sativa var. longifolia",
        "description": "Crisp, elongated leaves ideal for Caesar salads. Heat tolerant variety.",
        "temperature_range": {"min": 16, "max": 24, "optimal": 20},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 0.8, "max": 1.4, "optimal": 1.2},
        "light_hours": {"min": 10, "max": 16, "optimal": 14},
        "days_to_harvest": 55,
        "yield_per_sqm": 5.0,
        "profit_margin": 32,
        "difficulty_level": "beginner",
        "water_consumption": "low",
        "nutrient_requirements": {"N": "medium", "P": "low", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["spring", "fall", "winter"],
        "climate_zones": ["temperate", "subtropical", "mediterranean"],
        "indian_regions": ["North India", "Central India", "Northeast"],
        "indian_states": ["Punjab", "Haryana", "UP", "MP", "Bihar"],
        "best_months_india": [1, 2, 3, 10, 11, 12],
        "common_pests": ["Aphids", "Thrips", "Caterpillars"],
        "common_diseases": ["Lettuce Mosaic Virus", "Bacterial Soft Rot"],
        "companion_crops": ["Chives", "Garlic", "Onions"],
        "market_demand": "high",
        "storage_days": 10,
        "nutritional_highlights": ["Vitamin A", "Vitamin C", "Fiber"],
        "tips": "More heat tolerant than other lettuces. Good for warmer climates.",
    },
    "spinach": {
        "name": "Spinach",
        "emoji": "🥬",
        "category": "leafy_greens",
        "scientific_name": "Spinacia oleracea",
        "description": "Nutrient-dense superfood. Excellent for hydroponics with fast growth.",
        "temperature_range": {"min": 10, "max": 21, "optimal": 16},
        "humidity_range": {"min": 45, "max": 65, "optimal": 55},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.8, "max": 2.3, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 40,
        "yield_per_sqm": 3.5,
        "profit_margin": 40,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "high"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["fall", "winter", "early_spring"],
        "climate_zones": ["temperate", "cool_subtropical"],
        "indian_regions": ["North India", "Hill Stations", "Northeast"],
        "indian_states": ["Punjab", "Haryana", "HP", "Uttarakhand", "Kashmir"],
        "best_months_india": [10, 11, 12, 1, 2],
        "common_pests": ["Leaf Miners", "Aphids", "Slugs"],
        "common_diseases": ["Downy Mildew", "Fusarium Wilt"],
        "companion_crops": ["Strawberries", "Peas", "Beans"],
        "market_demand": "very_high",
        "storage_days": 5,
        "nutritional_highlights": ["Iron", "Calcium", "Vitamin K", "Folate"],
        "tips": "Bolts quickly in hot weather. Maintain cool temperatures.",
    },
    "kale": {
        "name": "Kale",
        "emoji": "🥬",
        "category": "leafy_greens",
        "scientific_name": "Brassica oleracea var. sabellica",
        "description": "Superfood with high nutrient density. Cold tolerant and robust.",
        "temperature_range": {"min": 7, "max": 24, "optimal": 16},
        "humidity_range": {"min": 45, "max": 65, "optimal": 55},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 1.8, "max": 2.5, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 16, "optimal": 14},
        "days_to_harvest": 55,
        "yield_per_sqm": 3.0,
        "profit_margin": 45,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "high"},
        "best_hydroponic_systems": ["NFT", "DWC", "Dutch Bucket"],
        "growing_seasons": ["fall", "winter", "spring"],
        "climate_zones": ["temperate", "cool_subtropical", "highland_tropical"],
        "indian_regions": ["North India", "Hill Stations", "Northeast"],
        "indian_states": ["Himachal Pradesh", "Uttarakhand", "Sikkim", "Arunachal"],
        "best_months_india": [9, 10, 11, 12, 1, 2, 3],
        "common_pests": ["Cabbage Worms", "Aphids", "Flea Beetles"],
        "common_diseases": ["Black Rot", "Clubroot"],
        "companion_crops": ["Beets", "Celery", "Onions"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Vitamin K", "Vitamin C", "Antioxidants"],
        "tips": "Frost actually improves flavor. Very cold hardy.",
    },
    "swiss_chard": {
        "name": "Swiss Chard",
        "emoji": "🥬",
        "category": "leafy_greens",
        "scientific_name": "Beta vulgaris subsp. cicla",
        "description": "Colorful stems with large leaves. Heat and cold tolerant.",
        "temperature_range": {"min": 10, "max": 27, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.8, "max": 2.3, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 50,
        "yield_per_sqm": 4.0,
        "profit_margin": 38,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "high"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["temperate", "subtropical", "mediterranean"],
        "indian_regions": ["All India", "Hill Stations"],
        "indian_states": ["Maharashtra", "Karnataka", "Tamil Nadu", "Gujarat"],
        "best_months_india": [2, 3, 4, 9, 10, 11],
        "common_pests": ["Leaf Miners", "Aphids"],
        "common_diseases": ["Cercospora Leaf Spot"],
        "companion_crops": ["Beans", "Cabbage", "Onions"],
        "market_demand": "medium",
        "storage_days": 5,
        "nutritional_highlights": ["Vitamin K", "Magnesium", "Iron"],
        "tips": "Harvest outer leaves to promote continuous growth.",
    },
    "arugula": {
        "name": "Arugula (Rocket)",
        "emoji": "🥗",
        "category": "leafy_greens",
        "scientific_name": "Eruca vesicaria sativa",
        "description": "Peppery, nutty flavor. Fast growing and popular in salads.",
        "temperature_range": {"min": 10, "max": 22, "optimal": 16},
        "humidity_range": {"min": 50, "max": 65, "optimal": 55},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 0.8, "max": 1.4, "optimal": 1.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 30,
        "yield_per_sqm": 2.5,
        "profit_margin": 50,
        "difficulty_level": "beginner",
        "water_consumption": "low",
        "nutrient_requirements": {"N": "medium", "P": "low", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Wick"],
        "growing_seasons": ["spring", "fall", "winter"],
        "climate_zones": ["temperate", "mediterranean"],
        "indian_regions": ["North India", "Hill Stations"],
        "indian_states": ["Delhi NCR", "Punjab", "HP", "Uttarakhand"],
        "best_months_india": [10, 11, 12, 1, 2, 3],
        "common_pests": ["Flea Beetles", "Aphids"],
        "common_diseases": ["Downy Mildew"],
        "companion_crops": ["Beets", "Carrots", "Lettuce"],
        "market_demand": "high",
        "storage_days": 4,
        "nutritional_highlights": ["Vitamin K", "Folate", "Calcium"],
        "tips": "Bolts quickly in heat. Keep cool for best flavor.",
    },
    "bok_choy": {
        "name": "Bok Choy (Pak Choi)",
        "emoji": "🥬",
        "category": "leafy_greens",
        "scientific_name": "Brassica rapa subsp. chinensis",
        "description": "Chinese cabbage with mild flavor. Fast growing Asian green.",
        "temperature_range": {"min": 13, "max": 24, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.5, "optimal": 6.5},
        "ec_range": {"min": 1.5, "max": 2.5, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 45,
        "yield_per_sqm": 4.0,
        "profit_margin": 42,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["spring", "fall", "winter"],
        "climate_zones": ["temperate", "subtropical"],
        "indian_regions": ["Northeast", "North India", "Hill Stations"],
        "indian_states": ["Assam", "Meghalaya", "West Bengal", "Sikkim"],
        "best_months_india": [9, 10, 11, 12, 1, 2, 3],
        "common_pests": ["Aphids", "Caterpillars", "Flea Beetles"],
        "common_diseases": ["Clubroot", "Black Rot"],
        "companion_crops": ["Celery", "Potatoes", "Onions"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Vitamin C", "Vitamin A", "Calcium"],
        "tips": "Baby bok choy matures faster and has premium market value.",
    },
    "mustard_greens": {
        "name": "Mustard Greens (Sarson)",
        "emoji": "🥬",
        "category": "leafy_greens",
        "scientific_name": "Brassica juncea",
        "description": "Spicy, peppery leaves popular in Indian cuisine. Fast growing.",
        "temperature_range": {"min": 10, "max": 24, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.5, "max": 2.5, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 40,
        "yield_per_sqm": 3.5,
        "profit_margin": 35,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["fall", "winter"],
        "climate_zones": ["temperate", "subtropical"],
        "indian_regions": ["North India", "Central India"],
        "indian_states": ["Punjab", "Haryana", "UP", "Rajasthan", "MP"],
        "best_months_india": [10, 11, 12, 1, 2],
        "common_pests": ["Aphids", "Caterpillars", "Flea Beetles"],
        "common_diseases": ["White Rust", "Downy Mildew"],
        "companion_crops": ["Peas", "Carrots", "Onions"],
        "market_demand": "very_high",
        "storage_days": 5,
        "nutritional_highlights": ["Vitamin K", "Vitamin A", "Vitamin C"],
        "tips": "Very popular in Punjab for Sarson ka Saag. High local demand.",
    },
    "watercress": {
        "name": "Watercress",
        "emoji": "🌿",
        "category": "leafy_greens",
        "scientific_name": "Nasturtium officinale",
        "description": "Aquatic plant perfect for hydroponics. Peppery flavor.",
        "temperature_range": {"min": 10, "max": 20, "optimal": 15},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 6.5, "max": 7.5, "optimal": 7.0},
        "ec_range": {"min": 0.4, "max": 1.8, "optimal": 1.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 30,
        "yield_per_sqm": 2.0,
        "profit_margin": 55,
        "difficulty_level": "intermediate",
        "water_consumption": "very_high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["DWC", "NFT", "Raft"],
        "growing_seasons": ["spring", "fall", "winter"],
        "climate_zones": ["temperate", "cool_subtropical"],
        "indian_regions": ["Hill Stations", "Northeast"],
        "indian_states": ["HP", "Uttarakhand", "Kashmir", "Sikkim"],
        "best_months_india": [9, 10, 11, 12, 1, 2, 3, 4],
        "common_pests": ["Aphids", "Whiteflies"],
        "common_diseases": ["Crook Root"],
        "companion_crops": ["Mint", "Parsley"],
        "market_demand": "high",
        "storage_days": 3,
        "nutritional_highlights": ["Vitamin K", "Vitamin C", "Antioxidants"],
        "tips": "Naturally aquatic - thrives in water-based systems.",
    },
    "microgreens_mix": {
        "name": "Microgreens Mix",
        "emoji": "🌱",
        "category": "leafy_greens",
        "scientific_name": "Various",
        "description": "Young seedlings harvested early. Premium product with quick turnaround.",
        "temperature_range": {"min": 18, "max": 24, "optimal": 21},
        "humidity_range": {"min": 40, "max": 60, "optimal": 50},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 0.5, "max": 1.0, "optimal": 0.8},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 12,
        "yield_per_sqm": 1.5,
        "profit_margin": 70,
        "difficulty_level": "beginner",
        "water_consumption": "low",
        "nutrient_requirements": {"N": "low", "P": "low", "K": "low"},
        "best_hydroponic_systems": ["Tray", "NFT", "Vertical"],
        "growing_seasons": ["all_year"],
        "climate_zones": ["all"],
        "indian_regions": ["All India - Indoor"],
        "indian_states": ["All States"],
        "best_months_india": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "common_pests": ["Fungus Gnats"],
        "common_diseases": ["Damping Off"],
        "companion_crops": ["Any microgreen varieties"],
        "market_demand": "very_high",
        "storage_days": 5,
        "nutritional_highlights": ["Concentrated Nutrients", "Antioxidants"],
        "tips": "Fastest ROI crop. Popular with restaurants and health-conscious consumers.",
    },
    
    # ==================== HERBS ====================
    "basil_sweet": {
        "name": "Sweet Basil",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Ocimum basilicum",
        "description": "Essential culinary herb. Aromatic with sweet, peppery flavor.",
        "temperature_range": {"min": 18, "max": 30, "optimal": 24},
        "humidity_range": {"min": 40, "max": 60, "optimal": 50},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 1.0, "max": 1.6, "optimal": 1.2},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 28,
        "yield_per_sqm": 2.5,
        "profit_margin": 55,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Kratky"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["tropical", "subtropical", "temperate"],
        "indian_regions": ["All India"],
        "indian_states": ["All States"],
        "best_months_india": [2, 3, 4, 5, 6, 7, 8, 9, 10],
        "common_pests": ["Aphids", "Japanese Beetles", "Slugs"],
        "common_diseases": ["Fusarium Wilt", "Downy Mildew"],
        "companion_crops": ["Tomatoes", "Peppers", "Oregano"],
        "market_demand": "very_high",
        "storage_days": 5,
        "nutritional_highlights": ["Vitamin K", "Manganese", "Essential Oils"],
        "tips": "Pinch flowers to prolong harvest. Sensitive to cold.",
    },
    "basil_tulsi": {
        "name": "Holy Basil (Tulsi)",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Ocimum tenuiflorum",
        "description": "Sacred Indian herb with medicinal properties. Adaptogenic.",
        "temperature_range": {"min": 20, "max": 35, "optimal": 28},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.5, "optimal": 6.5},
        "ec_range": {"min": 1.0, "max": 1.6, "optimal": 1.2},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 40,
        "yield_per_sqm": 2.0,
        "profit_margin": 50,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Dutch Bucket"],
        "growing_seasons": ["spring", "summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["All India"],
        "indian_states": ["All States"],
        "best_months_india": [3, 4, 5, 6, 7, 8, 9, 10],
        "common_pests": ["Aphids", "Whiteflies"],
        "common_diseases": ["Powdery Mildew"],
        "companion_crops": ["Tomatoes", "Peppers"],
        "market_demand": "very_high",
        "storage_days": 4,
        "nutritional_highlights": ["Antioxidants", "Essential Oils", "Adaptogens"],
        "tips": "Highly revered in India. Both culinary and medicinal value.",
    },
    "mint_peppermint": {
        "name": "Peppermint",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Mentha × piperita",
        "description": "Refreshing mint with cooling sensation. Spreads vigorously.",
        "temperature_range": {"min": 13, "max": 24, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 7.0, "optimal": 6.0},
        "ec_range": {"min": 2.0, "max": 2.4, "optimal": 2.2},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 30,
        "yield_per_sqm": 3.0,
        "profit_margin": 45,
        "difficulty_level": "beginner",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["temperate", "subtropical"],
        "indian_regions": ["North India", "Hill Stations"],
        "indian_states": ["UP", "MP", "Punjab", "HP", "Uttarakhand"],
        "best_months_india": [2, 3, 4, 5, 9, 10, 11],
        "common_pests": ["Spider Mites", "Aphids"],
        "common_diseases": ["Rust", "Verticillium Wilt"],
        "companion_crops": ["Cabbage", "Tomatoes"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Menthol", "Rosmarinic Acid", "Vitamin A"],
        "tips": "Spreads aggressively - keep contained in hydroponics.",
    },
    "mint_pudina": {
        "name": "Spearmint (Pudina)",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Mentha spicata",
        "description": "Most common culinary mint in India. Essential for chutneys.",
        "temperature_range": {"min": 15, "max": 28, "optimal": 22},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 7.0, "optimal": 6.0},
        "ec_range": {"min": 2.0, "max": 2.4, "optimal": 2.2},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 28,
        "yield_per_sqm": 3.5,
        "profit_margin": 40,
        "difficulty_level": "beginner",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["all_year"],
        "climate_zones": ["tropical", "subtropical", "temperate"],
        "indian_regions": ["All India"],
        "indian_states": ["All States"],
        "best_months_india": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "common_pests": ["Spider Mites", "Aphids", "Caterpillars"],
        "common_diseases": ["Rust", "Powdery Mildew"],
        "companion_crops": ["Tomatoes", "Carrots", "Cabbage"],
        "market_demand": "very_high",
        "storage_days": 5,
        "nutritional_highlights": ["Vitamin A", "Iron", "Manganese"],
        "tips": "Extremely high demand in India. Essential kitchen herb.",
    },
    "coriander": {
        "name": "Coriander (Dhania)",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Coriandrum sativum",
        "description": "Most important herb in Indian cooking. Both leaves and seeds used.",
        "temperature_range": {"min": 15, "max": 25, "optimal": 20},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.2, "max": 1.8, "optimal": 1.5},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 35,
        "yield_per_sqm": 2.5,
        "profit_margin": 45,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["fall", "winter", "early_spring"],
        "climate_zones": ["temperate", "subtropical"],
        "indian_regions": ["All India"],
        "indian_states": ["Rajasthan", "Gujarat", "MP", "AP", "Karnataka"],
        "best_months_india": [10, 11, 12, 1, 2, 3],
        "common_pests": ["Aphids", "Whiteflies"],
        "common_diseases": ["Bacterial Leaf Spot", "Powdery Mildew"],
        "companion_crops": ["Spinach", "Lettuce", "Tomatoes"],
        "market_demand": "very_high",
        "storage_days": 5,
        "nutritional_highlights": ["Vitamin K", "Vitamin C", "Antioxidants"],
        "tips": "Bolts quickly in heat. Grow in cooler months for leaf production.",
    },
    "cilantro": {
        "name": "Cilantro",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Coriandrum sativum",
        "description": "Fresh coriander leaves. Slow-bolt varieties available for hydroponics.",
        "temperature_range": {"min": 10, "max": 22, "optimal": 16},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.2, "max": 1.8, "optimal": 1.5},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 30,
        "yield_per_sqm": 2.0,
        "profit_margin": 50,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["fall", "winter", "spring"],
        "climate_zones": ["temperate", "cool_subtropical"],
        "indian_regions": ["North India", "Central India"],
        "indian_states": ["Punjab", "Haryana", "UP", "MP", "Rajasthan"],
        "best_months_india": [10, 11, 12, 1, 2, 3],
        "common_pests": ["Aphids", "Leaf Hoppers"],
        "common_diseases": ["Leaf Spot", "Soft Rot"],
        "companion_crops": ["Tomatoes", "Peppers", "Beans"],
        "market_demand": "very_high",
        "storage_days": 4,
        "nutritional_highlights": ["Vitamin K", "Vitamin A", "Potassium"],
        "tips": "Use slow-bolt varieties for extended harvest.",
    },
    "parsley": {
        "name": "Parsley",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Petroselinum crispum",
        "description": "Versatile garnishing herb. Both flat-leaf and curly varieties.",
        "temperature_range": {"min": 10, "max": 24, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 0.8, "max": 1.8, "optimal": 1.4},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 75,
        "yield_per_sqm": 2.0,
        "profit_margin": 45,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["spring", "fall", "winter"],
        "climate_zones": ["temperate", "mediterranean"],
        "indian_regions": ["North India", "Hill Stations"],
        "indian_states": ["HP", "Uttarakhand", "Kashmir", "Delhi NCR"],
        "best_months_india": [9, 10, 11, 12, 1, 2, 3, 4],
        "common_pests": ["Aphids", "Carrot Fly"],
        "common_diseases": ["Septoria Leaf Spot", "Crown Rot"],
        "companion_crops": ["Tomatoes", "Asparagus", "Roses"],
        "market_demand": "high",
        "storage_days": 10,
        "nutritional_highlights": ["Vitamin K", "Vitamin C", "Iron"],
        "tips": "Slow to germinate. Start from transplants for faster production.",
    },
    "oregano": {
        "name": "Oregano",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Origanum vulgare",
        "description": "Mediterranean herb essential for Italian cuisine. Drought tolerant.",
        "temperature_range": {"min": 15, "max": 26, "optimal": 21},
        "humidity_range": {"min": 40, "max": 60, "optimal": 50},
        "ph_range": {"min": 6.0, "max": 8.0, "optimal": 7.0},
        "ec_range": {"min": 1.5, "max": 2.0, "optimal": 1.8},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 45,
        "yield_per_sqm": 2.0,
        "profit_margin": 50,
        "difficulty_level": "beginner",
        "water_consumption": "low",
        "nutrient_requirements": {"N": "low", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Kratky"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["mediterranean", "subtropical", "temperate"],
        "indian_regions": ["North India", "West India"],
        "indian_states": ["Maharashtra", "Gujarat", "Rajasthan", "HP"],
        "best_months_india": [2, 3, 4, 5, 9, 10, 11],
        "common_pests": ["Aphids", "Spider Mites"],
        "common_diseases": ["Root Rot"],
        "companion_crops": ["Peppers", "Tomatoes", "Basil"],
        "market_demand": "high",
        "storage_days": 14,
        "nutritional_highlights": ["Carvacrol", "Thymol", "Antioxidants"],
        "tips": "Prune regularly to prevent woodiness. Dries well.",
    },
    "thyme": {
        "name": "Thyme",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Thymus vulgaris",
        "description": "Aromatic perennial herb with tiny leaves. Essential in French cuisine.",
        "temperature_range": {"min": 10, "max": 24, "optimal": 18},
        "humidity_range": {"min": 40, "max": 60, "optimal": 50},
        "ph_range": {"min": 5.5, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 0.8, "max": 1.6, "optimal": 1.2},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 70,
        "yield_per_sqm": 1.5,
        "profit_margin": 55,
        "difficulty_level": "intermediate",
        "water_consumption": "low",
        "nutrient_requirements": {"N": "low", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Kratky"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["mediterranean", "temperate"],
        "indian_regions": ["Hill Stations", "North India"],
        "indian_states": ["HP", "Uttarakhand", "Kashmir"],
        "best_months_india": [2, 3, 4, 5, 9, 10, 11],
        "common_pests": ["Spider Mites", "Aphids"],
        "common_diseases": ["Root Rot", "Botrytis"],
        "companion_crops": ["Cabbage", "Strawberries", "Tomatoes"],
        "market_demand": "high",
        "storage_days": 14,
        "nutritional_highlights": ["Thymol", "Vitamin C", "Iron"],
        "tips": "Prefers well-drained conditions. Avoid overwatering.",
    },
    "rosemary": {
        "name": "Rosemary",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Salvia rosmarinus",
        "description": "Woody perennial with needle-like leaves. Strong pine-like aroma.",
        "temperature_range": {"min": 15, "max": 28, "optimal": 22},
        "humidity_range": {"min": 35, "max": 55, "optimal": 45},
        "ph_range": {"min": 5.5, "max": 7.5, "optimal": 6.5},
        "ec_range": {"min": 1.0, "max": 1.6, "optimal": 1.2},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 90,
        "yield_per_sqm": 1.5,
        "profit_margin": 50,
        "difficulty_level": "intermediate",
        "water_consumption": "low",
        "nutrient_requirements": {"N": "low", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["DWC", "Dutch Bucket", "Kratky"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["mediterranean", "subtropical"],
        "indian_regions": ["West India", "South India", "Hill Stations"],
        "indian_states": ["Maharashtra", "Karnataka", "HP", "Goa"],
        "best_months_india": [9, 10, 11, 12, 1, 2, 3, 4],
        "common_pests": ["Spider Mites", "Mealybugs"],
        "common_diseases": ["Powdery Mildew", "Root Rot"],
        "companion_crops": ["Carrots", "Cabbage", "Beans"],
        "market_demand": "high",
        "storage_days": 14,
        "nutritional_highlights": ["Rosmarinic Acid", "Carnosic Acid", "Iron"],
        "tips": "Slow growing but long-lived. Prefers drier conditions.",
    },
    "sage": {
        "name": "Sage",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Salvia officinalis",
        "description": "Aromatic herb with velvety leaves. Important in Mediterranean cooking.",
        "temperature_range": {"min": 12, "max": 24, "optimal": 18},
        "humidity_range": {"min": 40, "max": 60, "optimal": 50},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 1.0, "max": 1.6, "optimal": 1.4},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 75,
        "yield_per_sqm": 1.5,
        "profit_margin": 50,
        "difficulty_level": "intermediate",
        "water_consumption": "low",
        "nutrient_requirements": {"N": "low", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["DWC", "Dutch Bucket", "Kratky"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["mediterranean", "temperate"],
        "indian_regions": ["Hill Stations", "North India"],
        "indian_states": ["HP", "Uttarakhand", "Kashmir"],
        "best_months_india": [2, 3, 4, 5, 9, 10, 11],
        "common_pests": ["Spider Mites", "Slugs"],
        "common_diseases": ["Powdery Mildew", "Root Rot"],
        "companion_crops": ["Rosemary", "Carrots", "Cabbage"],
        "market_demand": "medium",
        "storage_days": 10,
        "nutritional_highlights": ["Vitamin K", "Rosmarinic Acid", "Antioxidants"],
        "tips": "Needs good air circulation. Prune to maintain shape.",
    },
    "chives": {
        "name": "Chives",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Allium schoenoprasum",
        "description": "Mild onion-flavored herb. Both leaves and flowers are edible.",
        "temperature_range": {"min": 10, "max": 24, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.8, "max": 2.4, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 60,
        "yield_per_sqm": 2.0,
        "profit_margin": 45,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["temperate", "cool_subtropical"],
        "indian_regions": ["North India", "Hill Stations"],
        "indian_states": ["HP", "Uttarakhand", "Kashmir", "Sikkim"],
        "best_months_india": [2, 3, 4, 5, 9, 10, 11],
        "common_pests": ["Onion Thrips", "Aphids"],
        "common_diseases": ["Downy Mildew", "Rust"],
        "companion_crops": ["Carrots", "Tomatoes", "Roses"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Vitamin K", "Vitamin C", "Allicin"],
        "tips": "Cut regularly to encourage new growth. Very cold hardy.",
    },
    "dill": {
        "name": "Dill (Sowa)",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Anethum graveolens",
        "description": "Feathery herb with distinctive flavor. Used in pickles and cuisine.",
        "temperature_range": {"min": 15, "max": 25, "optimal": 20},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 1.0, "max": 1.6, "optimal": 1.4},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 40,
        "yield_per_sqm": 2.0,
        "profit_margin": 40,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Dutch Bucket"],
        "growing_seasons": ["spring", "fall"],
        "climate_zones": ["temperate", "subtropical"],
        "indian_regions": ["North India", "Central India"],
        "indian_states": ["UP", "MP", "Rajasthan", "Gujarat"],
        "best_months_india": [10, 11, 12, 1, 2, 3],
        "common_pests": ["Aphids", "Caterpillars"],
        "common_diseases": ["Powdery Mildew"],
        "companion_crops": ["Cabbage", "Cucumbers", "Lettuce"],
        "market_demand": "medium",
        "storage_days": 5,
        "nutritional_highlights": ["Vitamin A", "Vitamin C", "Manganese"],
        "tips": "Bolts quickly in heat. Sow successively for continuous harvest.",
    },
    "fenugreek": {
        "name": "Fenugreek (Methi)",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Trigonella foenum-graecum",
        "description": "Essential Indian herb. Leaves and seeds both used extensively.",
        "temperature_range": {"min": 10, "max": 27, "optimal": 20},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.0, "max": 1.6, "optimal": 1.2},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 25,
        "yield_per_sqm": 2.5,
        "profit_margin": 45,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "low", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["fall", "winter", "spring"],
        "climate_zones": ["subtropical", "tropical", "temperate"],
        "indian_regions": ["All India"],
        "indian_states": ["Rajasthan", "Gujarat", "MP", "Maharashtra", "UP"],
        "best_months_india": [10, 11, 12, 1, 2, 3],
        "common_pests": ["Aphids", "Pod Borer"],
        "common_diseases": ["Root Rot", "Powdery Mildew"],
        "companion_crops": ["Spinach", "Mustard", "Coriander"],
        "market_demand": "very_high",
        "storage_days": 4,
        "nutritional_highlights": ["Iron", "Protein", "Fiber", "Diosgenin"],
        "tips": "Very popular in India. Fast growing with multiple harvests possible.",
    },
    "curry_leaves": {
        "name": "Curry Leaves (Kadi Patta)",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Murraya koenigii",
        "description": "Essential South Indian herb with distinctive aroma. Perennial shrub.",
        "temperature_range": {"min": 18, "max": 35, "optimal": 28},
        "humidity_range": {"min": 50, "max": 80, "optimal": 65},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.2, "max": 2.0, "optimal": 1.6},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 365,
        "yield_per_sqm": 1.5,
        "profit_margin": 60,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "DWC", "Kratky"],
        "growing_seasons": ["all_year"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["South India", "West India", "Central India"],
        "indian_states": ["Karnataka", "Tamil Nadu", "Kerala", "AP", "Maharashtra"],
        "best_months_india": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "common_pests": ["Scale Insects", "Aphids"],
        "common_diseases": ["Leaf Spot"],
        "companion_crops": ["Chilies", "Tomatoes"],
        "market_demand": "very_high",
        "storage_days": 7,
        "nutritional_highlights": ["Carbazole Alkaloids", "Iron", "Calcium"],
        "tips": "Perennial - once established provides continuous harvest.",
    },
    "lemongrass": {
        "name": "Lemongrass",
        "emoji": "🌿",
        "category": "herbs",
        "scientific_name": "Cymbopogon citratus",
        "description": "Aromatic grass with citrus flavor. Used in Asian cuisine and teas.",
        "temperature_range": {"min": 20, "max": 35, "optimal": 28},
        "humidity_range": {"min": 50, "max": 80, "optimal": 65},
        "ph_range": {"min": 5.5, "max": 7.5, "optimal": 6.5},
        "ec_range": {"min": 1.5, "max": 2.5, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 100,
        "yield_per_sqm": 3.0,
        "profit_margin": 40,
        "difficulty_level": "beginner",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "DWC", "Ebb and Flow"],
        "growing_seasons": ["spring", "summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["South India", "Northeast", "Coastal Areas"],
        "indian_states": ["Kerala", "Karnataka", "Assam", "West Bengal", "Goa"],
        "best_months_india": [2, 3, 4, 5, 6, 7, 8, 9, 10],
        "common_pests": ["Mealybugs", "Spider Mites"],
        "common_diseases": ["Rust", "Leaf Blight"],
        "companion_crops": ["Ginger", "Turmeric"],
        "market_demand": "high",
        "storage_days": 14,
        "nutritional_highlights": ["Citral", "Antioxidants", "Essential Oils"],
        "tips": "Propagate from stalks. Grows vigorously in warm conditions.",
    },

    # ==================== FRUITING VEGETABLES ====================
    "tomato_cherry": {
        "name": "Cherry Tomatoes",
        "emoji": "🍅",
        "category": "fruiting_vegetables",
        "scientific_name": "Solanum lycopersicum var. cerasiforme",
        "description": "Sweet, bite-sized tomatoes. Prolific producer ideal for hydroponics.",
        "temperature_range": {"min": 18, "max": 30, "optimal": 24},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 2.0, "max": 5.0, "optimal": 3.5},
        "light_hours": {"min": 12, "max": 18, "optimal": 16},
        "days_to_harvest": 65,
        "yield_per_sqm": 8.0,
        "profit_margin": 45,
        "difficulty_level": "intermediate",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "high", "K": "very_high"},
        "best_hydroponic_systems": ["Dutch Bucket", "DWC", "Drip"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["temperate", "subtropical", "tropical_highlands"],
        "indian_regions": ["All India"],
        "indian_states": ["Karnataka", "AP", "Maharashtra", "MP", "HP"],
        "best_months_india": [9, 10, 11, 12, 1, 2, 3],
        "common_pests": ["Tomato Hornworm", "Aphids", "Whiteflies"],
        "common_diseases": ["Blossom End Rot", "Early Blight", "Fusarium Wilt"],
        "companion_crops": ["Basil", "Carrots", "Parsley"],
        "market_demand": "very_high",
        "storage_days": 10,
        "nutritional_highlights": ["Lycopene", "Vitamin C", "Potassium"],
        "tips": "Requires trellising. Prune suckers for larger fruits.",
    },
    "tomato_beefsteak": {
        "name": "Beefsteak Tomatoes",
        "emoji": "🍅",
        "category": "fruiting_vegetables",
        "scientific_name": "Solanum lycopersicum",
        "description": "Large, meaty tomatoes perfect for slicing. Requires support.",
        "temperature_range": {"min": 18, "max": 29, "optimal": 24},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 2.5, "max": 5.0, "optimal": 4.0},
        "light_hours": {"min": 12, "max": 18, "optimal": 16},
        "days_to_harvest": 85,
        "yield_per_sqm": 12.0,
        "profit_margin": 40,
        "difficulty_level": "intermediate",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "high", "K": "very_high"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip", "Bato Bucket"],
        "growing_seasons": ["spring", "summer"],
        "climate_zones": ["temperate", "subtropical"],
        "indian_regions": ["North India", "Central India", "Hill Stations"],
        "indian_states": ["HP", "Uttarakhand", "Maharashtra", "MP"],
        "best_months_india": [9, 10, 11, 12, 1, 2],
        "common_pests": ["Tomato Fruitworm", "Aphids", "Spider Mites"],
        "common_diseases": ["Late Blight", "Verticillium Wilt"],
        "companion_crops": ["Basil", "Peppers", "Carrots"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Lycopene", "Vitamin A", "Vitamin C"],
        "tips": "Heavy feeders. Increase EC during fruiting.",
    },
    "bell_pepper": {
        "name": "Bell Pepper (Capsicum)",
        "emoji": "🫑",
        "category": "fruiting_vegetables",
        "scientific_name": "Capsicum annuum",
        "description": "Sweet, crunchy peppers. Available in green, red, yellow, orange.",
        "temperature_range": {"min": 18, "max": 30, "optimal": 24},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 6.8, "optimal": 6.2},
        "ec_range": {"min": 2.0, "max": 3.5, "optimal": 2.5},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 75,
        "yield_per_sqm": 6.0,
        "profit_margin": 50,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "high", "K": "high"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip", "DWC"],
        "growing_seasons": ["spring", "summer", "fall"],
        "climate_zones": ["temperate", "subtropical", "tropical_highlands"],
        "indian_regions": ["All India"],
        "indian_states": ["Karnataka", "Maharashtra", "HP", "Tamil Nadu"],
        "best_months_india": [8, 9, 10, 11, 12, 1, 2, 3],
        "common_pests": ["Aphids", "Thrips", "Spider Mites"],
        "common_diseases": ["Bacterial Spot", "Phytophthora"],
        "companion_crops": ["Tomatoes", "Basil", "Carrots"],
        "market_demand": "very_high",
        "storage_days": 14,
        "nutritional_highlights": ["Vitamin C", "Vitamin A", "Vitamin B6"],
        "tips": "Colored varieties fetch premium prices. Support needed.",
    },
    "chili_pepper": {
        "name": "Chili Pepper (Mirchi)",
        "emoji": "🌶️",
        "category": "fruiting_vegetables",
        "scientific_name": "Capsicum annuum/frutescens",
        "description": "Hot peppers essential in Indian cuisine. Many varieties available.",
        "temperature_range": {"min": 20, "max": 35, "optimal": 28},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 7.0, "optimal": 6.2},
        "ec_range": {"min": 2.0, "max": 3.5, "optimal": 2.5},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 70,
        "yield_per_sqm": 5.0,
        "profit_margin": 45,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "high", "K": "high"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip", "DWC"],
        "growing_seasons": ["spring", "summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["All India"],
        "indian_states": ["AP", "Karnataka", "Maharashtra", "MP", "Rajasthan"],
        "best_months_india": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "common_pests": ["Thrips", "Mites", "Fruit Borer"],
        "common_diseases": ["Anthracnose", "Bacterial Wilt"],
        "companion_crops": ["Tomatoes", "Basil", "Okra"],
        "market_demand": "very_high",
        "storage_days": 14,
        "nutritional_highlights": ["Capsaicin", "Vitamin C", "Vitamin A"],
        "tips": "Extremely high demand in India. Year-round crop possible.",
    },
    "cucumber": {
        "name": "Cucumber",
        "emoji": "🥒",
        "category": "fruiting_vegetables",
        "scientific_name": "Cucumis sativus",
        "description": "Refreshing vegetable with high water content. Fast growing.",
        "temperature_range": {"min": 20, "max": 32, "optimal": 26},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 1.7, "max": 2.5, "optimal": 2.0},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 55,
        "yield_per_sqm": 10.0,
        "profit_margin": 35,
        "difficulty_level": "intermediate",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "high"},
        "best_hydroponic_systems": ["Dutch Bucket", "NFT", "Drip"],
        "growing_seasons": ["spring", "summer"],
        "climate_zones": ["temperate", "subtropical", "tropical"],
        "indian_regions": ["All India"],
        "indian_states": ["UP", "Haryana", "AP", "Karnataka", "Maharashtra"],
        "best_months_india": [2, 3, 4, 5, 6, 7, 8, 9],
        "common_pests": ["Cucumber Beetle", "Aphids", "Spider Mites"],
        "common_diseases": ["Powdery Mildew", "Downy Mildew"],
        "companion_crops": ["Beans", "Peas", "Radishes"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Water", "Vitamin K", "Potassium"],
        "tips": "Use parthenocarpic varieties for hydroponics - no pollination needed.",
    },
    "eggplant": {
        "name": "Eggplant (Brinjal/Baingan)",
        "emoji": "🍆",
        "category": "fruiting_vegetables",
        "scientific_name": "Solanum melongena",
        "description": "Versatile vegetable in Indian cuisine. Multiple shapes and colors.",
        "temperature_range": {"min": 21, "max": 32, "optimal": 26},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 2.5, "max": 3.5, "optimal": 3.0},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 75,
        "yield_per_sqm": 8.0,
        "profit_margin": 40,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "high", "P": "high", "K": "high"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip", "DWC"],
        "growing_seasons": ["spring", "summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["All India"],
        "indian_states": ["West Bengal", "Odisha", "Bihar", "Gujarat", "Maharashtra"],
        "best_months_india": [2, 3, 4, 5, 6, 7, 8, 9, 10],
        "common_pests": ["Fruit and Shoot Borer", "Aphids", "Jassids"],
        "common_diseases": ["Bacterial Wilt", "Phomopsis Blight"],
        "companion_crops": ["Beans", "Peppers", "Spinach"],
        "market_demand": "very_high",
        "storage_days": 7,
        "nutritional_highlights": ["Fiber", "Potassium", "Manganese"],
        "tips": "Very popular in India. Requires consistent warmth.",
    },
    "okra": {
        "name": "Okra (Bhindi/Lady Finger)",
        "emoji": "🫛",
        "category": "fruiting_vegetables",
        "scientific_name": "Abelmoschus esculentus",
        "description": "Fast-growing warm season crop. Essential in Indian cuisine.",
        "temperature_range": {"min": 25, "max": 38, "optimal": 30},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.5, "optimal": 6.5},
        "ec_range": {"min": 2.0, "max": 2.4, "optimal": 2.2},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 55,
        "yield_per_sqm": 5.0,
        "profit_margin": 40,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "DWC", "Drip"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["All India"],
        "indian_states": ["Gujarat", "West Bengal", "Bihar", "AP", "Maharashtra"],
        "best_months_india": [2, 3, 4, 5, 6, 7, 8, 9],
        "common_pests": ["Fruit Borer", "Jassids", "Aphids"],
        "common_diseases": ["Yellow Vein Mosaic", "Powdery Mildew"],
        "companion_crops": ["Peppers", "Eggplant", "Melons"],
        "market_demand": "very_high",
        "storage_days": 5,
        "nutritional_highlights": ["Fiber", "Vitamin C", "Folate"],
        "tips": "Harvest young for tender pods. Daily harvesting needed.",
    },
    "zucchini": {
        "name": "Zucchini",
        "emoji": "🥒",
        "category": "fruiting_vegetables",
        "scientific_name": "Cucurbita pepo",
        "description": "Prolific summer squash. Mild flavor and versatile use.",
        "temperature_range": {"min": 18, "max": 30, "optimal": 24},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.5, "optimal": 6.5},
        "ec_range": {"min": 1.8, "max": 2.4, "optimal": 2.0},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 50,
        "yield_per_sqm": 8.0,
        "profit_margin": 35,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "DWC", "Drip"],
        "growing_seasons": ["spring", "summer"],
        "climate_zones": ["temperate", "subtropical"],
        "indian_regions": ["North India", "Hill Stations"],
        "indian_states": ["HP", "Uttarakhand", "Maharashtra", "Karnataka"],
        "best_months_india": [2, 3, 4, 5, 9, 10],
        "common_pests": ["Squash Vine Borer", "Squash Bugs", "Aphids"],
        "common_diseases": ["Powdery Mildew", "Blossom End Rot"],
        "companion_crops": ["Beans", "Corn", "Dill"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Vitamin C", "Potassium", "Manganese"],
        "tips": "Harvest when small for best texture. Very productive.",
    },
    "strawberry": {
        "name": "Strawberry",
        "emoji": "🍓",
        "category": "fruiting_vegetables",
        "scientific_name": "Fragaria × ananassa",
        "description": "High-value berry crop. Excellent for vertical hydroponics.",
        "temperature_range": {"min": 15, "max": 26, "optimal": 20},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 5.5, "max": 6.5, "optimal": 6.0},
        "ec_range": {"min": 1.0, "max": 1.5, "optimal": 1.2},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 90,
        "yield_per_sqm": 3.0,
        "profit_margin": 65,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "high", "K": "high"},
        "best_hydroponic_systems": ["NFT", "Vertical Towers", "Dutch Bucket"],
        "growing_seasons": ["fall", "winter", "spring"],
        "climate_zones": ["temperate", "cool_subtropical"],
        "indian_regions": ["Hill Stations", "North India"],
        "indian_states": ["HP", "Uttarakhand", "Kashmir", "Maharashtra", "Karnataka"],
        "best_months_india": [9, 10, 11, 12, 1, 2, 3],
        "common_pests": ["Spider Mites", "Aphids", "Thrips"],
        "common_diseases": ["Botrytis", "Powdery Mildew", "Root Rot"],
        "companion_crops": ["Lettuce", "Spinach", "Beans"],
        "market_demand": "very_high",
        "storage_days": 5,
        "nutritional_highlights": ["Vitamin C", "Manganese", "Folate", "Antioxidants"],
        "tips": "Premium crop with high ROI. Needs day-neutral varieties for year-round.",
    },

    # ==================== ROOT VEGETABLES (Hydroponic Adapted) ====================
    "radish": {
        "name": "Radish (Mooli)",
        "emoji": "🥕",
        "category": "root_vegetables",
        "scientific_name": "Raphanus sativus",
        "description": "Fast-growing root vegetable. Can be grown in deep water systems.",
        "temperature_range": {"min": 10, "max": 24, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.6, "max": 2.2, "optimal": 1.8},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 30,
        "yield_per_sqm": 4.0,
        "profit_margin": 30,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "low", "P": "medium", "K": "high"},
        "best_hydroponic_systems": ["Dutch Bucket", "DWC", "Flood and Drain"],
        "growing_seasons": ["fall", "winter", "spring"],
        "climate_zones": ["temperate", "subtropical"],
        "indian_regions": ["North India", "Central India"],
        "indian_states": ["UP", "Punjab", "Haryana", "Bihar", "MP"],
        "best_months_india": [9, 10, 11, 12, 1, 2],
        "common_pests": ["Flea Beetles", "Cabbage Maggot"],
        "common_diseases": ["Black Root", "Clubroot"],
        "companion_crops": ["Carrots", "Lettuce", "Peas"],
        "market_demand": "high",
        "storage_days": 14,
        "nutritional_highlights": ["Vitamin C", "Potassium", "Folate"],
        "tips": "Fast crop for quick turnaround. Avoid nitrogen excess.",
    },
    "green_onion": {
        "name": "Green Onion (Spring Onion)",
        "emoji": "🧅",
        "category": "root_vegetables",
        "scientific_name": "Allium fistulosum",
        "description": "Bunching onion grown for green tops. Continuous harvest possible.",
        "temperature_range": {"min": 13, "max": 27, "optimal": 20},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.4, "max": 1.8, "optimal": 1.6},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 45,
        "yield_per_sqm": 3.0,
        "profit_margin": 40,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Flood and Drain"],
        "growing_seasons": ["all_year"],
        "climate_zones": ["temperate", "subtropical", "tropical"],
        "indian_regions": ["All India"],
        "indian_states": ["Maharashtra", "Karnataka", "MP", "Bihar", "Gujarat"],
        "best_months_india": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "common_pests": ["Thrips", "Onion Fly"],
        "common_diseases": ["Downy Mildew", "Purple Blotch"],
        "companion_crops": ["Carrots", "Beets", "Lettuce"],
        "market_demand": "high",
        "storage_days": 10,
        "nutritional_highlights": ["Vitamin K", "Vitamin C", "Folate"],
        "tips": "Can be harvested multiple times by cutting above base.",
    },
    "beet": {
        "name": "Beetroot (Chukandar)",
        "emoji": "🥕",
        "category": "root_vegetables",
        "scientific_name": "Beta vulgaris",
        "description": "Nutritious root vegetable. Both roots and greens are edible.",
        "temperature_range": {"min": 10, "max": 24, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 0.8, "max": 5.0, "optimal": 2.5},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 60,
        "yield_per_sqm": 4.0,
        "profit_margin": 35,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "high"},
        "best_hydroponic_systems": ["Dutch Bucket", "DWC", "Ebb and Flow"],
        "growing_seasons": ["fall", "winter", "spring"],
        "climate_zones": ["temperate", "cool_subtropical"],
        "indian_regions": ["North India", "Hill Stations"],
        "indian_states": ["UP", "Punjab", "Haryana", "HP", "West Bengal"],
        "best_months_india": [9, 10, 11, 12, 1, 2, 3],
        "common_pests": ["Leaf Miners", "Aphids"],
        "common_diseases": ["Cercospora Leaf Spot"],
        "companion_crops": ["Cabbage", "Beans", "Lettuce"],
        "market_demand": "high",
        "storage_days": 21,
        "nutritional_highlights": ["Nitrates", "Folate", "Manganese", "Betalains"],
        "tips": "Needs boron. Greens can be harvested while root develops.",
    },
    "carrot": {
        "name": "Carrot (Gajar)",
        "emoji": "🥕",
        "category": "root_vegetables",
        "scientific_name": "Daucus carota",
        "description": "Popular root vegetable rich in beta-carotene. Challenging in hydroponics.",
        "temperature_range": {"min": 10, "max": 24, "optimal": 18},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 6.8, "optimal": 6.3},
        "ec_range": {"min": 1.6, "max": 2.0, "optimal": 1.8},
        "light_hours": {"min": 10, "max": 16, "optimal": 12},
        "days_to_harvest": 75,
        "yield_per_sqm": 5.0,
        "profit_margin": 35,
        "difficulty_level": "advanced",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "low", "P": "medium", "K": "high"},
        "best_hydroponic_systems": ["Dutch Bucket", "Deep containers", "Aeroponics"],
        "growing_seasons": ["fall", "winter"],
        "climate_zones": ["temperate", "cool_subtropical"],
        "indian_regions": ["North India", "Hill Stations"],
        "indian_states": ["UP", "Punjab", "Haryana", "HP", "Uttarakhand"],
        "best_months_india": [9, 10, 11, 12, 1, 2],
        "common_pests": ["Carrot Fly", "Aphids"],
        "common_diseases": ["Alternaria Leaf Blight"],
        "companion_crops": ["Lettuce", "Onions", "Tomatoes"],
        "market_demand": "very_high",
        "storage_days": 28,
        "nutritional_highlights": ["Beta-Carotene", "Vitamin K", "Potassium"],
        "tips": "Requires deep containers. Use short varieties for hydroponics.",
    },

    # ==================== ASIAN VEGETABLES ====================
    "bitter_gourd": {
        "name": "Bitter Gourd (Karela)",
        "emoji": "🥬",
        "category": "asian_vegetables",
        "scientific_name": "Momordica charantia",
        "description": "Medicinal vegetable with bitter taste. Important in Indian cuisine.",
        "temperature_range": {"min": 24, "max": 35, "optimal": 30},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 6.0, "max": 6.7, "optimal": 6.3},
        "ec_range": {"min": 2.0, "max": 2.5, "optimal": 2.2},
        "light_hours": {"min": 12, "max": 14, "optimal": 13},
        "days_to_harvest": 60,
        "yield_per_sqm": 5.0,
        "profit_margin": 45,
        "difficulty_level": "intermediate",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "high"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip", "DWC"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["All India"],
        "indian_states": ["AP", "Odisha", "West Bengal", "Bihar", "UP"],
        "best_months_india": [2, 3, 4, 5, 6, 7, 8, 9],
        "common_pests": ["Fruit Fly", "Aphids"],
        "common_diseases": ["Powdery Mildew", "Downy Mildew"],
        "companion_crops": ["Beans", "Corn"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Charantin", "Vitamin C", "Iron", "Antidiabetic compounds"],
        "tips": "Needs trellising. Medicinal value increases market price.",
    },
    "bottle_gourd": {
        "name": "Bottle Gourd (Lauki/Dudhi)",
        "emoji": "🥒",
        "category": "asian_vegetables",
        "scientific_name": "Lagenaria siceraria",
        "description": "Light, nutritious gourd popular in Indian cooking. Vigorous vine.",
        "temperature_range": {"min": 24, "max": 35, "optimal": 30},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.8, "max": 2.4, "optimal": 2.0},
        "light_hours": {"min": 12, "max": 16, "optimal": 14},
        "days_to_harvest": 65,
        "yield_per_sqm": 8.0,
        "profit_margin": 35,
        "difficulty_level": "intermediate",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["All India"],
        "indian_states": ["UP", "Bihar", "Gujarat", "Maharashtra", "MP"],
        "best_months_india": [2, 3, 4, 5, 6, 7, 8],
        "common_pests": ["Fruit Fly", "Red Pumpkin Beetle"],
        "common_diseases": ["Downy Mildew", "Anthracnose"],
        "companion_crops": ["Corn", "Beans"],
        "market_demand": "high",
        "storage_days": 14,
        "nutritional_highlights": ["Water content", "Fiber", "Vitamin C"],
        "tips": "Requires sturdy trellis. Harvest young for tender texture.",
    },
    "ridge_gourd": {
        "name": "Ridge Gourd (Turai/Tori)",
        "emoji": "🥒",
        "category": "asian_vegetables",
        "scientific_name": "Luffa acutangula",
        "description": "Ribbed gourd popular in South Asian cuisine. Fast growing vine.",
        "temperature_range": {"min": 25, "max": 38, "optimal": 32},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.8, "max": 2.4, "optimal": 2.0},
        "light_hours": {"min": 12, "max": 14, "optimal": 13},
        "days_to_harvest": 50,
        "yield_per_sqm": 6.0,
        "profit_margin": 38,
        "difficulty_level": "intermediate",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["All India"],
        "indian_states": ["Gujarat", "Maharashtra", "AP", "Karnataka", "Tamil Nadu"],
        "best_months_india": [2, 3, 4, 5, 6, 7, 8, 9],
        "common_pests": ["Fruit Fly", "Aphids"],
        "common_diseases": ["Powdery Mildew"],
        "companion_crops": ["Beans", "Corn"],
        "market_demand": "high",
        "storage_days": 5,
        "nutritional_highlights": ["Fiber", "Vitamin A", "Iron"],
        "tips": "Harvest when young and tender. Daily harvesting needed.",
    },
    "snake_gourd": {
        "name": "Snake Gourd (Chichinda)",
        "emoji": "🥒",
        "category": "asian_vegetables",
        "scientific_name": "Trichosanthes cucumerina",
        "description": "Long, snake-like gourd with mild flavor. Unique appearance.",
        "temperature_range": {"min": 25, "max": 35, "optimal": 30},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.8, "max": 2.4, "optimal": 2.0},
        "light_hours": {"min": 12, "max": 14, "optimal": 13},
        "days_to_harvest": 55,
        "yield_per_sqm": 5.0,
        "profit_margin": 40,
        "difficulty_level": "intermediate",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["South India", "East India"],
        "indian_states": ["Tamil Nadu", "Kerala", "Karnataka", "AP", "West Bengal"],
        "best_months_india": [3, 4, 5, 6, 7, 8, 9],
        "common_pests": ["Fruit Fly", "Pumpkin Beetle"],
        "common_diseases": ["Downy Mildew"],
        "companion_crops": ["Beans", "Corn"],
        "market_demand": "medium",
        "storage_days": 5,
        "nutritional_highlights": ["Fiber", "Vitamin A", "Low Calories"],
        "tips": "Tie weights to growing fruits for straighter gourds.",
    },
    "ivy_gourd": {
        "name": "Ivy Gourd (Tindora/Kundru)",
        "emoji": "🥒",
        "category": "asian_vegetables",
        "scientific_name": "Coccinia grandis",
        "description": "Small, oval gourd very popular in West India. Perennial vine.",
        "temperature_range": {"min": 25, "max": 35, "optimal": 30},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.5, "max": 2.2, "optimal": 1.8},
        "light_hours": {"min": 12, "max": 14, "optimal": 13},
        "days_to_harvest": 60,
        "yield_per_sqm": 4.0,
        "profit_margin": 45,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip"],
        "growing_seasons": ["summer", "monsoon", "fall"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["West India", "South India"],
        "indian_states": ["Gujarat", "Maharashtra", "Karnataka", "Tamil Nadu"],
        "best_months_india": [3, 4, 5, 6, 7, 8, 9, 10],
        "common_pests": ["Fruit Fly"],
        "common_diseases": ["Leaf Spot"],
        "companion_crops": ["Beans", "Corn"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Beta-Carotene", "Fiber", "Antidiabetic properties"],
        "tips": "Perennial - provides continuous harvest. Well suited to Gujarat climate.",
    },
    "pointed_gourd": {
        "name": "Pointed Gourd (Parwal)",
        "emoji": "🥒",
        "category": "asian_vegetables",
        "scientific_name": "Trichosanthes dioica",
        "description": "Small pointed gourd very popular in East India. Perennial.",
        "temperature_range": {"min": 25, "max": 35, "optimal": 30},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.5, "max": 2.2, "optimal": 1.8},
        "light_hours": {"min": 12, "max": 14, "optimal": 13},
        "days_to_harvest": 90,
        "yield_per_sqm": 4.0,
        "profit_margin": 50,
        "difficulty_level": "intermediate",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "medium", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "Drip"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["East India", "North India"],
        "indian_states": ["Bihar", "UP", "West Bengal", "Jharkhand", "Odisha"],
        "best_months_india": [2, 3, 4, 5, 6, 7, 8, 9],
        "common_pests": ["Fruit Fly", "Aphids"],
        "common_diseases": ["Downy Mildew"],
        "companion_crops": ["Beans"],
        "market_demand": "high",
        "storage_days": 7,
        "nutritional_highlights": ["Vitamins A & C", "Fiber", "Low Calories"],
        "tips": "Dioecious - needs male/female plants or grafting. Commands premium prices.",
    },
    "ash_gourd": {
        "name": "Ash Gourd (Petha/Winter Melon)",
        "emoji": "🎃",
        "category": "asian_vegetables",
        "scientific_name": "Benincasa hispida",
        "description": "Large, waxy gourd used for sweet Petha. Long storage life.",
        "temperature_range": {"min": 24, "max": 35, "optimal": 30},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 6.0, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.8, "max": 2.4, "optimal": 2.0},
        "light_hours": {"min": 12, "max": 14, "optimal": 13},
        "days_to_harvest": 90,
        "yield_per_sqm": 10.0,
        "profit_margin": 35,
        "difficulty_level": "intermediate",
        "water_consumption": "high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "Ground-based"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["North India", "All India"],
        "indian_states": ["UP", "Bihar", "MP", "Rajasthan", "Gujarat"],
        "best_months_india": [2, 3, 4, 5, 6, 7],
        "common_pests": ["Fruit Fly", "Red Pumpkin Beetle"],
        "common_diseases": ["Powdery Mildew"],
        "companion_crops": ["Corn", "Beans"],
        "market_demand": "high",
        "storage_days": 180,
        "nutritional_highlights": ["92% Water", "Low Calories", "Cooling effect"],
        "tips": "Famous for Agra Petha. Very long storage life.",
    },

    # ==================== ASIAN LEAFY VEGETABLES ====================
    "kangkong": {
        "name": "Water Spinach (Kangkong)",
        "emoji": "🥬",
        "category": "asian_vegetables",
        "scientific_name": "Ipomoea aquatica",
        "description": "Semi-aquatic vegetable ideal for hydroponics. Fast growing.",
        "temperature_range": {"min": 25, "max": 35, "optimal": 30},
        "humidity_range": {"min": 70, "max": 90, "optimal": 80},
        "ph_range": {"min": 5.5, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.5, "max": 2.5, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 30,
        "yield_per_sqm": 4.0,
        "profit_margin": 40,
        "difficulty_level": "beginner",
        "water_consumption": "very_high",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["DWC", "NFT", "Raft"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["South India", "East India", "Northeast"],
        "indian_states": ["Kerala", "Tamil Nadu", "West Bengal", "Assam"],
        "best_months_india": [3, 4, 5, 6, 7, 8, 9, 10],
        "common_pests": ["Aphids", "Caterpillars"],
        "common_diseases": ["White Rust"],
        "companion_crops": ["Rice", "Water-loving plants"],
        "market_demand": "high",
        "storage_days": 3,
        "nutritional_highlights": ["Iron", "Vitamin A", "Vitamin C"],
        "tips": "Perfect for water-based hydroponics. Very fast growing.",
    },
    "amaranth": {
        "name": "Amaranth (Chaulai/Lal Saag)",
        "emoji": "🥬",
        "category": "asian_vegetables",
        "scientific_name": "Amaranthus tricolor",
        "description": "Colorful, nutritious leafy green. Heat tolerant superfood.",
        "temperature_range": {"min": 22, "max": 35, "optimal": 28},
        "humidity_range": {"min": 50, "max": 70, "optimal": 60},
        "ph_range": {"min": 6.0, "max": 7.5, "optimal": 6.8},
        "ec_range": {"min": 1.5, "max": 2.5, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 35,
        "yield_per_sqm": 3.5,
        "profit_margin": 40,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["NFT", "DWC", "Ebb and Flow"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["All India"],
        "indian_states": ["Bihar", "UP", "West Bengal", "Maharashtra", "Gujarat"],
        "best_months_india": [3, 4, 5, 6, 7, 8, 9],
        "common_pests": ["Aphids", "Caterpillars"],
        "common_diseases": ["Leaf Spot"],
        "companion_crops": ["Corn", "Tomatoes"],
        "market_demand": "high",
        "storage_days": 4,
        "nutritional_highlights": ["Protein", "Iron", "Calcium", "Vitamin A"],
        "tips": "Heat tolerant - grows well when lettuce bolts. Multiple cuts possible.",
    },
    "malabar_spinach": {
        "name": "Malabar Spinach (Poi Saag)",
        "emoji": "🥬",
        "category": "asian_vegetables",
        "scientific_name": "Basella alba",
        "description": "Climbing vine with fleshy leaves. Heat-loving spinach alternative.",
        "temperature_range": {"min": 25, "max": 35, "optimal": 30},
        "humidity_range": {"min": 60, "max": 80, "optimal": 70},
        "ph_range": {"min": 5.5, "max": 7.0, "optimal": 6.5},
        "ec_range": {"min": 1.5, "max": 2.5, "optimal": 2.0},
        "light_hours": {"min": 10, "max": 14, "optimal": 12},
        "days_to_harvest": 50,
        "yield_per_sqm": 4.0,
        "profit_margin": 35,
        "difficulty_level": "beginner",
        "water_consumption": "medium",
        "nutrient_requirements": {"N": "high", "P": "medium", "K": "medium"},
        "best_hydroponic_systems": ["Dutch Bucket", "DWC", "NFT"],
        "growing_seasons": ["summer", "monsoon"],
        "climate_zones": ["tropical", "subtropical"],
        "indian_regions": ["East India", "South India"],
        "indian_states": ["West Bengal", "Odisha", "Bihar", "Kerala", "Tamil Nadu"],
        "best_months_india": [4, 5, 6, 7, 8, 9, 10],
        "common_pests": ["Caterpillars"],
        "common_diseases": ["Leaf Spot"],
        "companion_crops": ["Climbing beans"],
        "market_demand": "medium",
        "storage_days": 3,
        "nutritional_highlights": ["Mucilage", "Vitamin A", "Iron", "Calcium"],
        "tips": "Needs trellis support. Thrives in heat when spinach bolts.",
    },
}

# ==================== CLIMATE ZONES IN INDIA ====================

INDIAN_CLIMATE_ZONES = {
    "tropical_wet": {
        "name": "Tropical Wet",
        "description": "Heavy rainfall, high humidity year-round",
        "states": ["Kerala", "Coastal Karnataka", "Goa", "Andaman & Nicobar"],
        "temperature_range": {"min": 22, "max": 35},
        "best_seasons": ["monsoon", "winter"],
    },
    "tropical_dry": {
        "name": "Tropical Dry", 
        "description": "Hot summers, moderate winters, low rainfall",
        "states": ["Tamil Nadu", "AP", "Telangana", "Karnataka Interior"],
        "temperature_range": {"min": 20, "max": 42},
        "best_seasons": ["winter", "spring"],
    },
    "subtropical_humid": {
        "name": "Subtropical Humid",
        "description": "Hot humid summers, mild winters",
        "states": ["West Bengal", "Odisha", "Bihar", "Jharkhand", "Eastern UP"],
        "temperature_range": {"min": 10, "max": 40},
        "best_seasons": ["winter", "spring"],
    },
    "subtropical_dry": {
        "name": "Subtropical Dry (Semi-Arid)",
        "description": "Hot summers, cool winters, low rainfall",
        "states": ["Gujarat", "Rajasthan", "Western MP", "Haryana", "Punjab"],
        "temperature_range": {"min": 5, "max": 45},
        "best_seasons": ["winter"],
    },
    "temperate": {
        "name": "Temperate",
        "description": "Cool climate with distinct seasons",
        "states": ["Himachal Pradesh", "Uttarakhand", "Kashmir", "Sikkim", "Arunachal"],
        "temperature_range": {"min": -5, "max": 30},
        "best_seasons": ["spring", "summer", "fall"],
    },
    "alpine": {
        "name": "Alpine/Cold Desert",
        "description": "Very cold, low rainfall, high altitude",
        "states": ["Ladakh", "Spiti", "Northern Sikkim"],
        "temperature_range": {"min": -30, "max": 20},
        "best_seasons": ["summer"],
    },
}

# ==================== SEASONAL MAPPING ====================

INDIAN_SEASONS = {
    "winter": {"months": [12, 1, 2], "name": "Winter (Rabi)"},
    "spring": {"months": [3, 4], "name": "Spring"},
    "summer": {"months": [4, 5, 6], "name": "Summer"},
    "monsoon": {"months": [7, 8, 9], "name": "Monsoon (Kharif)"},
    "fall": {"months": [10, 11], "name": "Autumn"},
}

# ==================== STATE TO CLIMATE MAPPING ====================

STATE_CLIMATE_MAP = {
    "Andhra Pradesh": "tropical_dry",
    "Arunachal Pradesh": "temperate",
    "Assam": "subtropical_humid",
    "Bihar": "subtropical_humid",
    "Chhattisgarh": "subtropical_humid",
    "Goa": "tropical_wet",
    "Gujarat": "subtropical_dry",
    "Haryana": "subtropical_dry",
    "Himachal Pradesh": "temperate",
    "Jharkhand": "subtropical_humid",
    "Karnataka": "tropical_dry",
    "Kerala": "tropical_wet",
    "Madhya Pradesh": "subtropical_dry",
    "Maharashtra": "tropical_dry",
    "Manipur": "subtropical_humid",
    "Meghalaya": "subtropical_humid",
    "Mizoram": "subtropical_humid",
    "Nagaland": "subtropical_humid",
    "Odisha": "subtropical_humid",
    "Punjab": "subtropical_dry",
    "Rajasthan": "subtropical_dry",
    "Sikkim": "temperate",
    "Tamil Nadu": "tropical_dry",
    "Telangana": "tropical_dry",
    "Tripura": "subtropical_humid",
    "Uttar Pradesh": "subtropical_dry",
    "Uttarakhand": "temperate",
    "West Bengal": "subtropical_humid",
    "Delhi": "subtropical_dry",
    "Jammu and Kashmir": "temperate",
    "Ladakh": "alpine",
}


class CropRecommendationEngine:
    """
    AI-powered crop recommendation engine for hydroponics
    Recommends crops based on location, climate, season, and growing conditions
    """
    
    def __init__(self):
        self.crops = HYDROPONIC_CROPS
        self.climates = INDIAN_CLIMATE_ZONES
        self.seasons = INDIAN_SEASONS
        self.state_climate = STATE_CLIMATE_MAP
    
    def get_current_season(self, month: int = None) -> str:
        """Get the current growing season based on month"""
        if month is None:
            month = datetime.now().month
        
        for season, data in self.seasons.items():
            if month in data["months"]:
                return season
        return "winter"
    
    def get_climate_for_state(self, state: str) -> str:
        """Get climate zone for a given Indian state"""
        # Handle partial matches
        state_lower = state.lower()
        for s, climate in self.state_climate.items():
            if state_lower in s.lower() or s.lower() in state_lower:
                return climate
        return "subtropical_humid"  # Default
    
    def calculate_crop_score(
        self,
        crop_data: Dict,
        temperature: float,
        humidity: float,
        ph: float,
        state: str = None,
        month: int = None
    ) -> float:
        """
        Calculate a compatibility score for a crop based on conditions
        Returns a score from 0-100
        """
        score = 0.0
        
        # Temperature score (35 points max)
        temp_range = crop_data.get("temperature_range", {})
        temp_min = temp_range.get("min", 15)
        temp_max = temp_range.get("max", 30)
        temp_opt = temp_range.get("optimal", 22)
        
        if temp_min <= temperature <= temp_max:
            # Within range - calculate closeness to optimal
            if temperature == temp_opt:
                score += 35
            else:
                deviation = abs(temperature - temp_opt)
                max_deviation = max(temp_opt - temp_min, temp_max - temp_opt)
                score += 35 * (1 - deviation / max_deviation)
        else:
            # Outside range - penalize
            if temperature < temp_min:
                deviation = temp_min - temperature
            else:
                deviation = temperature - temp_max
            # Up to 10 degrees outside range gives some score
            if deviation <= 10:
                score += max(0, 15 - deviation * 1.5)
        
        # Humidity score (20 points max)
        humidity_range = crop_data.get("humidity_range", {})
        hum_min = humidity_range.get("min", 50)
        hum_max = humidity_range.get("max", 70)
        hum_opt = humidity_range.get("optimal", 60)
        
        if hum_min <= humidity <= hum_max:
            deviation = abs(humidity - hum_opt)
            max_deviation = max(hum_opt - hum_min, hum_max - hum_opt)
            score += 20 * (1 - deviation / (max_deviation + 1))
        else:
            if humidity < hum_min:
                deviation = hum_min - humidity
            else:
                deviation = humidity - hum_max
            if deviation <= 15:
                score += max(0, 10 - deviation * 0.5)
        
        # pH score (25 points max)
        ph_range = crop_data.get("ph_range", {})
        ph_min = ph_range.get("min", 5.5)
        ph_max = ph_range.get("max", 6.5)
        ph_opt = ph_range.get("optimal", 6.0)
        
        if ph_min <= ph <= ph_max:
            deviation = abs(ph - ph_opt)
            max_deviation = max(ph_opt - ph_min, ph_max - ph_opt)
            score += 25 * (1 - deviation / (max_deviation + 0.1))
        else:
            if ph < ph_min:
                deviation = ph_min - ph
            else:
                deviation = ph - ph_max
            if deviation <= 1.0:
                score += max(0, 12 - deviation * 8)
        
        # Season score (10 points max)
        if month:
            current_season = self.get_current_season(month)
            growing_seasons = crop_data.get("growing_seasons", [])
            best_months = crop_data.get("best_months_india", [])
            
            if "all_year" in growing_seasons:
                score += 10
            elif current_season in growing_seasons:
                score += 10
            elif month in best_months:
                score += 10
            else:
                # Check adjacent seasons
                for season in growing_seasons:
                    season_months = self.seasons.get(season, {}).get("months", [])
                    if any(abs(month - m) <= 1 or abs(month - m) >= 11 for m in season_months):
                        score += 5
                        break
        else:
            score += 5  # Default if no month specified
        
        # State/region bonus (10 points max)
        if state:
            indian_states = crop_data.get("indian_states", [])
            indian_regions = crop_data.get("indian_regions", [])
            
            state_lower = state.lower()
            if any(state_lower in s.lower() for s in indian_states):
                score += 10
            elif any(s.lower() in state_lower for s in indian_states):
                score += 10
            elif "All India" in indian_regions or "All States" in indian_states:
                score += 8
            else:
                # Check if climate matches
                state_climate = self.get_climate_for_state(state)
                crop_climates = crop_data.get("climate_zones", [])
                if state_climate in crop_climates or any(c in state_climate for c in crop_climates):
                    score += 6
        else:
            score += 5  # Default
        
        return min(100, max(0, score))
    
    def get_recommendations(
        self,
        temperature: float,
        humidity: float,
        ph: float,
        state: str = None,
        month: int = None,
        category: str = None,
        difficulty: str = None,
        count: int = 10
    ) -> List[Dict]:
        """
        Get crop recommendations sorted by compatibility score
        
        Args:
            temperature: Current/expected temperature in Celsius
            humidity: Current/expected humidity percentage
            ph: Water pH level
            state: Indian state name
            month: Month number (1-12), defaults to current month
            category: Filter by category (leafy_greens, herbs, fruiting_vegetables, etc.)
            difficulty: Filter by difficulty (beginner, intermediate, advanced)
            count: Number of recommendations to return
        
        Returns:
            List of crop recommendations with scores
        """
        if month is None:
            month = datetime.now().month
        
        recommendations = []
        
        for crop_id, crop_data in self.crops.items():
            # Apply filters
            if category and crop_data.get("category") != category:
                continue
            if difficulty and crop_data.get("difficulty_level") != difficulty:
                continue
            
            # Calculate score
            score = self.calculate_crop_score(
                crop_data,
                temperature,
                humidity,
                ph,
                state,
                month
            )
            
            # Create recommendation object
            recommendation = {
                "id": crop_id,
                "name": crop_data.get("name"),
                "emoji": crop_data.get("emoji"),
                "category": crop_data.get("category"),
                "scientific_name": crop_data.get("scientific_name"),
                "description": crop_data.get("description"),
                "compatibility_score": round(score, 1),
                "difficulty_level": crop_data.get("difficulty_level"),
                "days_to_harvest": crop_data.get("days_to_harvest"),
                "yield_per_sqm": crop_data.get("yield_per_sqm"),
                "profit_margin": crop_data.get("profit_margin"),
                "water_consumption": crop_data.get("water_consumption"),
                "market_demand": crop_data.get("market_demand"),
                "best_hydroponic_systems": crop_data.get("best_hydroponic_systems"),
                "temperature_range": crop_data.get("temperature_range"),
                "humidity_range": crop_data.get("humidity_range"),
                "ph_range": crop_data.get("ph_range"),
                "ec_range": crop_data.get("ec_range"),
                "light_hours": crop_data.get("light_hours"),
                "nutrient_requirements": crop_data.get("nutrient_requirements"),
                "growing_seasons": crop_data.get("growing_seasons"),
                "common_pests": crop_data.get("common_pests"),
                "common_diseases": crop_data.get("common_diseases"),
                "companion_crops": crop_data.get("companion_crops"),
                "storage_days": crop_data.get("storage_days"),
                "nutritional_highlights": crop_data.get("nutritional_highlights"),
                "tips": crop_data.get("tips"),
            }
            
            recommendations.append(recommendation)
        
        # Sort by score (highest first)
        recommendations.sort(key=lambda x: x["compatibility_score"], reverse=True)
        
        return recommendations[:count]
    
    def get_crop_details(self, crop_id: str) -> Optional[Dict]:
        """Get detailed information about a specific crop"""
        if crop_id in self.crops:
            crop_data = self.crops[crop_id]
            return {
                "id": crop_id,
                **crop_data
            }
        return None
    
    def get_all_crops(self) -> List[Dict]:
        """Get all crops in the database"""
        return [
            {"id": crop_id, **crop_data}
            for crop_id, crop_data in self.crops.items()
        ]
    
    def get_crops_by_category(self, category: str) -> List[Dict]:
        """Get all crops in a specific category"""
        return [
            {"id": crop_id, **crop_data}
            for crop_id, crop_data in self.crops.items()
            if crop_data.get("category") == category
        ]
    
    def get_categories(self) -> List[str]:
        """Get all available crop categories"""
        categories = set()
        for crop_data in self.crops.values():
            if "category" in crop_data:
                categories.add(crop_data["category"])
        return list(categories)
    
    def get_seasonal_recommendations(
        self,
        state: str,
        month: int = None
    ) -> Dict:
        """Get seasonal crop recommendations for a state"""
        if month is None:
            month = datetime.now().month
        
        season = self.get_current_season(month)
        climate = self.get_climate_for_state(state)
        
        # Default conditions based on climate
        climate_data = self.climates.get(climate, {})
        temp_range = climate_data.get("temperature_range", {"min": 20, "max": 35})
        
        # Estimate current temperature based on month and climate
        # Simple seasonal adjustment
        if month in [12, 1, 2]:  # Winter
            temperature = temp_range["min"] + 5
        elif month in [4, 5, 6]:  # Summer
            temperature = temp_range["max"] - 5
        else:
            temperature = (temp_range["min"] + temp_range["max"]) / 2
        
        # Default humidity and pH
        humidity = 60
        ph = 6.0
        
        recommendations = self.get_recommendations(
            temperature=temperature,
            humidity=humidity,
            ph=ph,
            state=state,
            month=month,
            count=15
        )
        
        return {
            "state": state,
            "season": season,
            "climate_zone": climate,
            "estimated_temperature": temperature,
            "recommendations": recommendations
        }


# Export the engine and data
recommendation_engine = CropRecommendationEngine()
