import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'marketplace_model.dart';

final marketplaceProductsProvider = Provider<List<MarketplaceProduct>>((ref) {
  return [
    // ============== NUTRIENTS & SOLUTIONS ==============
    MarketplaceProduct(
      id: '1',
      name: 'Basic NPK Nutrient Solution 5L 💰 CHEAPEST',
      category: 'Nutrients',
      price: 450,
      rating: 4.2,
      reviewCount: 89,
      icon: '🧪',
      description: 'Budget NPK solution - perfect for beginners',
      redirectUrl:
          'https://www.indiamart.com/proddetail/hydroponic-nutrient-solution-npk-23-19-18-23018558848.html',
      source: 'indiamart',
    ),
    MarketplaceProduct(
      id: '2',
      name: 'Hydroponic Nutrient Solution 5L',
      category: 'Nutrients',
      price: 550,
      rating: 4.4,
      reviewCount: 124,
      icon: '🧪',
      description: 'Good quality NPK solution for hydroponics',
      redirectUrl: 'https://www.jiomart.com/search/hydroponic+nutrient',
      source: 'jiomart',
    ),
    MarketplaceProduct(
      id: '3',
      name: 'General Hydroponics Flora Series',
      category: 'Nutrients',
      price: 1200,
      rating: 4.8,
      reviewCount: 156,
      icon: '🧫',
      description: 'Premium complete nutrient system',
      redirectUrl:
          'https://www.flipkart.com/search?q=general+hydroponics+flora',
      source: 'flipkart',
    ),

    // ============== MONITORING EQUIPMENT ==============
    MarketplaceProduct(
      id: '4',
      name: 'Basic pH Meter 💰 CHEAPEST',
      category: 'Monitoring',
      price: 350,
      rating: 4.0,
      reviewCount: 45,
      icon: '📏',
      description: 'Simple pH measurement - budget option',
      redirectUrl: 'https://m.olx.in/search?q=ph+meter+hydroponics',
      source: 'olx',
    ),
    MarketplaceProduct(
      id: '5',
      name: 'Digital pH Meter',
      category: 'Monitoring',
      price: 750,
      rating: 4.5,
      reviewCount: 78,
      icon: '📏',
      description: 'Accurate pH measurement device',
      redirectUrl: 'https://www.meesho.com/search?q=digital+ph+meter',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '6',
      name: 'Premium pH Meter Pro',
      category: 'Monitoring',
      price: 1200,
      rating: 4.8,
      reviewCount: 89,
      icon: '📏',
      description: 'Professional pH meter with calibration solutions',
      redirectUrl:
          'https://www.flipkart.com/search?q=digital+ph+meter+professional',
      source: 'flipkart',
    ),
    MarketplaceProduct(
      id: '7',
      name: 'EC/TDS Meter Budget 💰 CHEAPEST',
      category: 'Monitoring',
      price: 400,
      rating: 4.1,
      reviewCount: 52,
      icon: '📊',
      description: 'Basic EC/TDS measurement',
      redirectUrl: 'https://www.meesho.com/search?q=tds+meter+digital',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '8',
      name: 'EC/TDS Meter Digital',
      category: 'Monitoring',
      price: 650,
      rating: 4.5,
      reviewCount: 90,
      icon: '📊',
      description: 'Reliable EC/TDS measurement',
      redirectUrl: 'https://www.jiomart.com/search/tds+meter',
      source: 'jiomart',
    ),
    MarketplaceProduct(
      id: '9',
      name: 'Thermometer Digital LCD 💰 CHEAPEST',
      category: 'Monitoring',
      price: 80,
      rating: 3.9,
      reviewCount: 67,
      icon: '🌡️',
      description: 'Basic temperature monitoring',
      redirectUrl: 'https://m.olx.in/search?q=digital+thermometer',
      source: 'olx',
    ),
    MarketplaceProduct(
      id: '10',
      name: 'Thermometer Digital LCD Aquarium',
      category: 'Monitoring',
      price: 150,
      rating: 4.3,
      reviewCount: 98,
      icon: '🌡️',
      description: 'Quality temperature monitor',
      redirectUrl:
          'https://www.flipkart.com/search?q=aquarium+thermometer+digital',
      source: 'flipkart',
    ),

    // ============== LIGHTING ==============
    MarketplaceProduct(
      id: '11',
      name: 'LED Grow Light 50W Budget 💰 CHEAPEST',
      category: 'Lighting',
      price: 1200,
      rating: 4.0,
      reviewCount: 67,
      icon: '💡',
      description: 'Basic LED grow light - budget option',
      redirectUrl: 'https://www.meesho.com/search?q=led+grow+light',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '12',
      name: 'LED Grow Light 100W',
      category: 'Lighting',
      price: 2500,
      rating: 4.4,
      reviewCount: 134,
      icon: '💡',
      description: 'Good quality full spectrum LED',
      redirectUrl: 'https://www.jiomart.com/search/led+grow+light+100w',
      source: 'jiomart',
    ),
    MarketplaceProduct(
      id: '13',
      name: 'LED Grow Light 100W Premium',
      category: 'Lighting',
      price: 3500,
      rating: 4.6,
      reviewCount: 156,
      icon: '💡',
      description: 'Premium full spectrum LED',
      redirectUrl: 'https://www.flipkart.com/search?q=led+grow+light+100w',
      source: 'flipkart',
    ),
    MarketplaceProduct(
      id: '14',
      name: 'LED Grow Light 200W',
      category: 'Lighting',
      price: 6500,
      rating: 4.7,
      reviewCount: 203,
      icon: '💡',
      description: 'High-power LED for large setups',
      redirectUrl: 'https://www.flipkart.com/search?q=led+grow+light+200w',
      source: 'flipkart',
    ),

    // ============== EQUIPMENT ==============
    MarketplaceProduct(
      id: '15',
      name: 'Water Pump 1000L/h Budget 💰 CHEAPEST',
      category: 'Equipment',
      price: 800,
      rating: 4.0,
      reviewCount: 45,
      icon: '💧',
      description: 'Basic submersible pump',
      redirectUrl: 'https://m.olx.in/search?q=water+pump+submersible',
      source: 'olx',
    ),
    MarketplaceProduct(
      id: '16',
      name: 'Water Pump 2000L/h',
      category: 'Equipment',
      price: 1400,
      rating: 4.3,
      reviewCount: 78,
      icon: '💧',
      description: 'Mid-range submersible pump',
      redirectUrl: 'https://www.meesho.com/search?q=water+pump+2000',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '17',
      name: 'Water Pump 3000L/h Submersible',
      category: 'Equipment',
      price: 2200,
      rating: 4.4,
      reviewCount: 92,
      icon: '💧',
      description: 'High-capacity water pump',
      redirectUrl:
          'https://www.flipkart.com/search?q=submersible+water+pump+3000',
      source: 'flipkart',
    ),
    MarketplaceProduct(
      id: '18',
      name: 'Air Pump 600L/h Budget 💰 CHEAPEST',
      category: 'Equipment',
      price: 300,
      rating: 4.0,
      reviewCount: 56,
      icon: '❄️',
      description: 'Basic aquarium air pump',
      redirectUrl: 'https://www.meesho.com/search?q=air+pump+aquarium',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '19',
      name: 'Air Pump 1200L/h Aquarium',
      category: 'Equipment',
      price: 650,
      rating: 4.3,
      reviewCount: 145,
      icon: '❄️',
      description: 'Good air pump for DWC systems',
      redirectUrl: 'https://www.jiomart.com/search/air+pump',
      source: 'jiomart',
    ),
    MarketplaceProduct(
      id: '20',
      name: 'Grow Tent 2x2 Budget 💰 CHEAPEST',
      category: 'Equipment',
      price: 2500,
      rating: 4.1,
      reviewCount: 78,
      icon: '⛺',
      description: 'Basic grow tent - budget option',
      redirectUrl: 'https://www.meesho.com/search?q=grow+tent+2x2',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '21',
      name: 'Grow Tent 2x2x2 Reflective',
      category: 'Equipment',
      price: 4500,
      rating: 4.5,
      reviewCount: 112,
      icon: '⛺',
      description: 'Premium grow tent with lining',
      redirectUrl: 'https://www.flipkart.com/search?q=grow+tent+2x2',
      source: 'flipkart',
    ),

    // ============== SEEDS ==============
    MarketplaceProduct(
      id: '22',
      name: 'Lettuce Seeds Budget Pack 💰 CHEAPEST',
      category: 'Seeds',
      price: 50,
      rating: 4.0,
      reviewCount: 34,
      icon: '🥬',
      description: 'Basic lettuce seeds - affordable',
      redirectUrl: 'https://m.olx.in/search?q=lettuce+seeds',
      source: 'olx',
    ),
    MarketplaceProduct(
      id: '23',
      name: 'Hydroponic Lettuce Seeds',
      category: 'Seeds',
      price: 120,
      rating: 4.4,
      reviewCount: 167,
      icon: '🥬',
      description: 'Quality hydroponic lettuce seeds',
      redirectUrl: 'https://www.meesho.com/search?q=lettuce+seeds',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '24',
      name: 'Hydroponic Lettuce Seeds Premium',
      category: 'Seeds',
      price: 150,
      rating: 4.7,
      reviewCount: 234,
      icon: '🥬',
      description: 'Premium variety pack',
      redirectUrl: 'https://www.flipkart.com/search?q=lettuce+seeds+hydroponic',
      source: 'flipkart',
    ),
    MarketplaceProduct(
      id: '25',
      name: 'Cherry Tomato Seeds Budget 💰 CHEAPEST',
      category: 'Seeds',
      price: 80,
      rating: 4.1,
      reviewCount: 45,
      icon: '🍅',
      description: 'Affordable tomato seeds',
      redirectUrl: 'https://www.meesho.com/search?q=tomato+seeds',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '26',
      name: 'Cherry Tomato Hybrid Seeds',
      category: 'Seeds',
      price: 200,
      rating: 4.6,
      reviewCount: 167,
      icon: '🍅',
      description: 'Hybrid cherry tomato seeds',
      redirectUrl: 'https://www.flipkart.com/search?q=cherry+tomato+seeds',
      source: 'flipkart',
    ),
    MarketplaceProduct(
      id: '27',
      name: 'Basil Seeds Budget 💰 CHEAPEST',
      category: 'Seeds',
      price: 60,
      rating: 4.0,
      reviewCount: 42,
      icon: '🌿',
      description: 'Basic basil seeds',
      redirectUrl: 'https://m.olx.in/search?q=basil+seeds',
      source: 'olx',
    ),
    MarketplaceProduct(
      id: '28',
      name: 'Basil Seeds Organic',
      category: 'Seeds',
      price: 180,
      rating: 4.5,
      reviewCount: 145,
      icon: '🌿',
      description: 'Organic basil for hydroponics',
      redirectUrl: 'https://www.flipkart.com/search?q=basil+seeds+organic',
      source: 'flipkart',
    ),

    // ============== GROWING MEDIA ==============
    MarketplaceProduct(
      id: '29',
      name: 'Rockwool Cubes Budget 💰 CHEAPEST',
      category: 'Growing Media',
      price: 200,
      rating: 4.0,
      reviewCount: 56,
      icon: '🪨',
      description: 'Budget rockwool for germination',
      redirectUrl: 'https://www.meesho.com/search?q=rockwool+cubes',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '30',
      name: 'Rockwool Hydroponic Cubes',
      category: 'Growing Media',
      price: 400,
      rating: 4.3,
      reviewCount: 89,
      icon: '🪨',
      description: 'Quality rockwool medium',
      redirectUrl: 'https://www.jiomart.com/search/rockwool+cubes',
      source: 'jiomart',
    ),
    MarketplaceProduct(
      id: '31',
      name: 'Expanded Clay Pebbles 10kg Budget',
      category: 'Growing Media',
      price: 600,
      rating: 4.2,
      reviewCount: 78,
      icon: '⚪',
      description: 'Budget clay pebbles',
      redirectUrl: 'https://www.meesho.com/search?q=clay+pebbles',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '32',
      name: 'Expanded Clay Pebbles 25kg',
      category: 'Growing Media',
      price: 1200,
      rating: 4.6,
      reviewCount: 156,
      icon: '⚪',
      description: 'Premium clay for systems',
      redirectUrl: 'https://www.flipkart.com/search?q=expanded+clay+pebbles',
      source: 'flipkart',
    ),

    // ============== SYSTEMS ==============
    MarketplaceProduct(
      id: '33',
      name: 'Basic DWC System Budget 💰 CHEAPEST',
      category: 'Systems',
      price: 1500,
      rating: 4.0,
      reviewCount: 45,
      icon: '🪠',
      description: 'Simple DWC setup - DIY friendly',
      redirectUrl: 'https://m.olx.in/search?q=dwc+hydroponics',
      source: 'olx',
    ),
    MarketplaceProduct(
      id: '34',
      name: 'DWC Deep Water Culture System',
      category: 'Systems',
      price: 3200,
      rating: 4.5,
      reviewCount: 89,
      icon: '🪠',
      description: 'Ready-to-use DWC system',
      redirectUrl: 'https://www.flipkart.com/search?q=dwc+hydroponics+system',
      source: 'flipkart',
    ),
    MarketplaceProduct(
      id: '35',
      name: 'NFT Channel System Budget 💰 CHEAPEST',
      category: 'Systems',
      price: 2500,
      rating: 4.1,
      reviewCount: 67,
      icon: '🏗️',
      description: 'Basic NFT setup',
      redirectUrl: 'https://www.meesho.com/search?q=nft+hydroponics',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '36',
      name: 'NFT Channel Hydroponics Kit',
      category: 'Systems',
      price: 4800,
      rating: 4.6,
      reviewCount: 134,
      icon: '🏗️',
      description: 'Commercial NFT system',
      redirectUrl: 'https://www.flipkart.com/search?q=nft+hydroponics+channel',
      source: 'flipkart',
    ),
    MarketplaceProduct(
      id: '37',
      name: 'Budget Starter Kit 💰 CHEAPEST',
      category: 'Kits',
      price: 3500,
      rating: 4.0,
      reviewCount: 89,
      icon: '📦',
      description: 'Basic hydroponic starter kit',
      redirectUrl: 'https://www.meesho.com/search?q=hydroponics+starter+kit',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '38',
      name: 'Complete Hydroponics Starter Kit',
      category: 'Kits',
      price: 8500,
      rating: 4.8,
      reviewCount: 412,
      icon: '📦',
      description: 'Premium all-in-one system',
      redirectUrl: 'https://www.amazon.in/s?k=hydroponic+starter+kit',
      source: 'amazon',
    ),

    // ============== MAINTENANCE ==============
    MarketplaceProduct(
      id: '39',
      name: 'pH Buffer Solution Basic 💰 CHEAPEST',
      category: 'Maintenance',
      price: 150,
      rating: 3.9,
      reviewCount: 42,
      icon: '⚗️',
      description: 'Budget pH buffers',
      redirectUrl: 'https://m.olx.in/search?q=ph+buffer+solution',
      source: 'olx',
    ),
    MarketplaceProduct(
      id: '40',
      name: 'pH Buffer Solution Set',
      category: 'Maintenance',
      price: 300,
      rating: 4.2,
      reviewCount: 76,
      icon: '⚗️',
      description: 'Quality pH buffers',
      redirectUrl: 'https://www.meesho.com/search?q=ph+buffer',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '41',
      name: 'Disease Prevention Organic 💰 CHEAPEST',
      category: 'Maintenance',
      price: 250,
      rating: 4.0,
      reviewCount: 56,
      icon: '🛡️',
      description: 'Budget pest control',
      redirectUrl: 'https://www.meesho.com/search?q=organic+pest+control',
      source: 'meesho',
    ),
    MarketplaceProduct(
      id: '42',
      name: 'Plant Disease Prevention Kit',
      category: 'Maintenance',
      price: 650,
      rating: 4.3,
      reviewCount: 98,
      icon: '🛡️',
      description: 'Complete disease prevention',
      redirectUrl:
          'https://www.flipkart.com/search?q=organic+plant+disease+prevention',
      source: 'flipkart',
    ),
  ];
});
