// File generated by FlutterFire CLI.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahSCB0e8nGl6coPbFPWMZeMqTIZLGVWQ',
    appId: '1:738579176126:web:b9738edbd2854b56595cef',
    messagingSenderId: '738579176126',
    projectId: 'hydroappsmart',
    authDomain: 'hydroappsmart.firebaseapp.com',
    storageBucket: 'hydroappsmart.firebasestorage.app',
    measurementId: 'G-1JJB9XPJX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE4NqZAUph-e5-NFXLng9gh-fuwzmwQiM',
    appId: '1:738579176126:android:5069a79abfd32e6c595cef',
    messagingSenderId: '738579176126',
    projectId: 'hydroappsmart',
    storageBucket: 'hydroappsmart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXH42NK9kSsU60zZnDZNfdmyTzen_cSqE',
    appId: '1:738579176126:ios:3a522bef6ab5f3d5595cef',
    messagingSenderId: '738579176126',
    projectId: 'hydroappsmart',
    storageBucket: 'hydroappsmart.firebasestorage.app',
    iosBundleId: 'com.example.hydroSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXH42NK9kSsU60zZnDZNfdmyTzen_cSqE',
    appId: '1:738579176126:ios:3a522bef6ab5f3d5595cef',
    messagingSenderId: '738579176126',
    projectId: 'hydroappsmart',
    storageBucket: 'hydroappsmart.firebasestorage.app',
    iosBundleId: 'com.example.hydroSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBahSCB0e8nGl6coPbFPWMZeMqTIZLGVWQ',
    appId: '1:738579176126:web:77fe83e0601d76d4595cef',
    messagingSenderId: '738579176126',
    projectId: 'hydroappsmart',
    authDomain: 'hydroappsmart.firebaseapp.com',
    storageBucket: 'hydroappsmart.firebasestorage.app',
    measurementId: 'G-BVRNL6CYYM',
  );
}
